spring.application.name=SkillExchange
server.port=8181

# MongoDB Atlas connection
# Separate these two lines!
spring.data.mongodb.uri=mongodb://localhost:27017/skill_xchange_db2
spring.data.mongodb.database=skill_xchange_db2

# Logging
logging.level.org.springframework.data.mongodb=DEBUG
spring.web.resources.add-mappings=false
gemini.api.key=AIzaSyDc8PR4iw0vkCFdmJ5aEcFm88SBjKJs14M

# Groq API Config
groq.api.url=https://api.groq.com/openai/v1/chat/completions
groq.api.key=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
groq.model=llama-3.1-8b-instant